export default {
    FETCH_USERS_STARTED: 'FETCH_USERS_STARTED',
    FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
    FETCH_USERS_FAILURE: 'FETCH_USERS_FAILURE',

    CHANGE_CURRENT_PAGE: 'CHANGE_CURRENT_PAGE',
    CHANGE_USER_PER_PAGE_VALUE: 'CHANGE_USER_PER_PAGE_VALUE',
};